services:
  windows-xp:
    image: dockurr/windows
    container_name: windows-xp
    environment:
      VERSION: ${VERSION}
      CPU_CORES: ${CPU_CORES}
      RAM_SIZE: ${RAM_SIZE}
      DISK_SIZE: ${DISK_SIZE}
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
      LANGUAGE: ${LANGUAGE}
      WIDTH: ${WIDTH}
      HEIGHT: ${HEIGHT}
      AUDIO: ${AUDIO}
      DISPLAY: ${DISPLAY}
      BOOT_MODE: ${BOOT_MODE}
      KVM: "N"
    ports:
      - "8006:8006"
    volumes:
      - ./data:/storage
    restart: always
    stop_grace_period: 2m
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.windows-xp.loadbalancer.server.port=8006"
