services:
  windows-xp:
    build: .
    container_name: windows-xp
    environment:
      RAM_SIZE: ${RAM_SIZE:-512}
      CPU_CORES: ${CPU_CORES:-1}
      DISK_SIZE: ${DISK_SIZE:-16G}
      RESOLUTION: ${RESOLUTION:-1024x768}
    ports:
      - "8006:8006"
      - "3389:3389"
    volumes:
      - ./data:/storage
    restart: always
    stop_grace_period: 2m
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.windows-xp.loadbalancer.server.port=8006"
