[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:qemu]
command=/opt/start.sh
autostart=true
autorestart=true
stdout_logfile=/var/log/qemu.log
stderr_logfile=/var/log/qemu_err.log

[program:websockify]
command=/opt/noVNC/utils/novnc_proxy --vnc localhost:5900 --listen 8006
autostart=true
autorestart=true
